# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tanner's Driving School
email: tannersdrivingschool@gmail.com
description: Tanner's is promoting a Carroll County, Maryland film project entitled "Crystal Falls Drive", focused on raising awareness for suicide prevention among teens.
logo: img/tds-logo-vertical.png
social: 
    name: Crystal Falls Drive
    links:
      - https://www.facebook.com/CrystalFallsDrive
      - https://www.youtube.com/channel/UCp6mt91UA88KjMGOBacO-GQ
      - https://www.kickstarter.com/projects/victorpekar/crystal-falls-drive
      - https://www.gofundme.com/f/crystal-falls-drive-film-submission


lang: en_US
domain: tannersdrivingschool.com
baseurl: ""
url: "https://tannersdrivingschool.com"


sass:
  style: compact

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
